keys:
  - &primary age1eevyne6xh9mxk0asuk2wyymneesch4jmfwf7wlea2pq8tszxkp2sqcdw97

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *primary